[tool.poetry]
name = "uorc-codedevelopment"
version = "0.1.0"
description = "Developing code for UORC"
authors = ["Kevin Chen <kevin.chen@telethonkids.org.au>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ipykernel = "^6.29.5"
openai = "^1.37.0"
biopython = "^1.84"
tqdm = "^4.66.4"
pandas = "^2.2.2"
wheel = "^0.43.0"
python-dotenv = "^1.0.1"
instructor = "^1.3.7"
asyncio = "^3.4.3"
h5py = "^3.11.0"
pydeseq2 = "^0.4.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
