[project]
name = "uorca"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bio>=1.7.1",
    "logfire>=3.9.0",
    "matplotlib>=3.10.1",
    "pydantic-ai>=0.0.48",
    "tiktoken>=0.9.0",
]

[tool.uv.workspace]
members = ["lib/memory", "lib/data_identification", "lib/data_extraction", "lib/data_analysis"]
