# MCP Server Configuration for UORCA RNA-seq Analysis

[servers.data_extractor]
enabled = true
path = "mcp_servers/mcp_data_extractor.py"
description = "Low-level data extraction from RNA-seq results"

[servers.analysis]
enabled = true
path = "mcp_servers/mcp_analysis.py"
description = "Higher-level analysis and pattern recognition"

# Example configuration for additional servers
# [servers.memory]
# enabled = false
# path = "mcp_servers/mcp_memory.py"
# description = "Memory/knowledge base server"